### ISSUE TITLE
Authentication improvements

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-workshop-server#11]
- [x] create JWTs instead of static token (simply use `{ client: 'tomster-player' }` as token payload)
- [x] remove account_id from token response
- [x] validate token on requests to albums, songs and comments (validate that `client` from JWT payload is `tomster-player`)

**Comment by ganeshbsub** [comment]
Somehow not able to split the string returned from get_req_header("authorization") to "Bearer" and <token>. Returns a pattern matching error.

**Comment by marcoow** [comment]
@ganeshbsub: I fixed it: b5c76d1f8df2ead4e6fe5393c5c2e964fa589ecf

Just need to make sure that any exception that is thrown in that plug results in a 401 response.
