### ISSUE TITLE
Make sure the app supports the JSON API content type

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-workshop-server#4]
Requests will be made with the

```
Accept:application/vnd.api+json
```

That should also be set as

```
Content-Type: application/vnd.api+json
```

for the response.

**Comment by ganeshbsub** [comment]
Done. Updated API here ->
https://dry-castle-5299.herokuapp.com/api/albums
https://dry-castle-5299.herokuapp.com/api/songs
