### ISSUE TITLE
Allow CORS

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-workshop-server#5]
The app must allow all kinds of CORS requests - all origins etc. Maybe e.g. this works: https://github.com/mschae/cors_plug. You can just allow everything - all origins, all headers etc.

**Comment by ganeshbsub** [comment]
Done. Updated API here ->
https://dry-castle-5299.herokuapp.com/api/albums
https://dry-castle-5299.herokuapp.com/api/songs
